queue_rules:
  - name: "MergeMe1"
    conditions: []

pull_request_rules:
  - name: Automatic merge
    conditions:
      - and:
        - "#commits-behind=0"
        - -conflict
    actions:
      queue:
        name: "MergeMe1"
        method: rebase
  - name: Rebase when out of date
    conditions:
      - and:
        - "#commits-behind>0"
        - -conflict
    actions:
      rebase:
