pull_request_rules:
  - name: Automatic merge ⬇️ on approval ✔
    conditions:
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: merge
  - name: Rebase when out of date
    conditions:
      - "#commits-behind>=1"
    actions:
      rebase:
        method: merge
